### ISSUE TITLE
getaddrinfo ENOTFOUND artifactory.rsglab.com

### ISSUE THREAD

**Issue by loan-laux** [reactioncommerce/api-core#18]
Prerequisites
* [x] Are you running the latest version?
* [x] Are you able to consistently reproduce the issue?
* [x] Did you search the issue queue for existing issue? [Search issues]

## Issue Description
When attaching a local `api-core` with `/bin/package-link`, NPM complains about not being able to resolve `artifactory.rsglab.com`. Upon doing a `whois`, it looks like `rsglab.com` is a domain registered by MailChimp. Is this some kind of internal NPM repo that the team is using? Or is `artifactory.rsglab.com ` supposed to be publicly accessible?

## Steps to Reproduce
1. Clone `api-core` locally.
2. Run `/bin/package-link @reactioncommerce/api-core` from your `reaction` directory.
3. Notice how NPM fails to resolve `artifactory.rsglab.com`, throwing `npm ERR! network request to https://artifactory.rsglab.com:443/artifactory/api/npm/npm/zen-observable-ts/-/zen-observable-ts-0.8.21.tgz failed, reason: getaddrinfo ENOTFOUND artifactory.rsglab.com`.

## Possible Solution
Use the normal NPM URLs for packages in `package-lock.json`.

**Comment by Akarshit** [comment]
The solution was to create a `.npmrc` file with `registry=https://registry.npmjs.org/`
